# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    ignore:
      # These libraries are tighly couple together, they should be managed manually
      - dependency-name: "androidx.compose.compiler:compiler"
      - dependency-name: "org.jetbrains.compose*"
      - dependency-name: "org.jetbrains.kotlin*"
      # These libraries are no longer supported
      - dependency-name: "org.mockito*"
      - dependency-name: "org.apache.commons*"
      - dependency-name: "org.assertj*"
